FastFood/Models/Cafe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FastFood.Models
{
    public class Cafe
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MainPhotoLocation { get; set; }
        public double Rating { get; set; }
        public int Review { get; set; }

        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        public List<Review> Reviews { get; set; }
        public List<Photo> Photos { get; set; }
    }
}

FastFood/Controllers/CafeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FastFood.Data;
using FastFood.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace FastFood.Controllers
{
    public class CafeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;
        private readonly UserManager<ApplicationUser> _userManager;

        public CafeController(ApplicationDbContext context, IHostingEnvironment environment, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _environment = environment;
            _userManager = userManager;
        }

        // GET: Cafe
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Cafes.Include(c => c.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Cafe/Details/5
        public async Task<IActionResult> Details(int? id, List<Photo> photos)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            //var cafe = await _context.Cafes
            //    .Include(c => c.User)
            //    .SingleOrDefaultAsync(m => m.Id == id);
            //if (cafe == null)
            //{
            //    return NotFound();
            //}

            //return View(cafe);
            
            Cafe cafe = _context.Cafes.Include(t => t.Reviews).Include(t => t.User).FirstOrDefault(t => t.Id == id);
            cafe.Photos = _context.Photos.Where(i => i.CafeId == id).ToList();
            CafeDetailsViewModel model = new CafeDetailsViewModel()
            {
                Cafe = cafe,
                ReviewsViewModel = new ReviewsViewModel()
                {
                    CafeId = cafe.Id,
                    Reviews = cafe.Reviews,
                    NewReview = new Review() { CafeId = cafe.Id }
                }
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Review(int cafeId, string reviewText)
        {
            Review review = new Review();
            review.ReviewDate = DateTime.Now;
            Cafe cafe = _context.Cafes.FirstOrDefault(t => t.Id == cafeId);
            cafe.Review++;
            _context.Cafes.Update(cafe);
            review.Cafe = cafe;
            review.ReviewText = reviewText;
            _context.Reviews.Add(review);
            _context.SaveChanges();
            return Json(reviewText);
        }

        // GET: Cafe/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Cafe/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Rating,UserId")] Cafe cafe, List<IFormFile> cafeFiles)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cafe);
                await _context.SaveChangesAsync();
                UploadFiles(cafe, cafeFiles);
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", cafe.UserId);
            return View(cafe);
        }


        public void UploadFiles(Cafe cafe, List<IFormFile> cafeFiles)
        {
            if (cafeFiles != null)
            {
                foreach (var element in cafeFiles)
                {
                    var fileName = Path.Combine(_environment.WebRootPath + "/images", Path.GetFileName(element.FileName));
                    element.CopyTo(new FileStream(fileName, FileMode.Create));
                    Photo photo = new Photo() { Location = fileName, UserId = cafe.UserId, CafeId = cafe.Id, Name = element.FileName };
                    _context.Photos.Add(photo);
                    _context.SaveChanges();
                }
            }
        }



        // GET: Cafe/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cafe = await _context.Cafes.SingleOrDefaultAsync(m => m.Id == id);
            if (cafe == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", cafe.UserId);
            return View(cafe);
        }

        // POST: Cafe/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Rating,UserId")] Cafe cafe)
        {
            if (id != cafe.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cafe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CafeExists(cafe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", cafe.UserId);
            return View(cafe);
        }

        // GET: Cafe/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cafe = await _context.Cafes
                .Include(c => c.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (cafe == null)
            {
                return NotFound();
            }

            return View(cafe);
        }

        // POST: Cafe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cafe = await _context.Cafes.SingleOrDefaultAsync(m => m.Id == id);
            _context.Cafes.Remove(cafe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CafeExists(int id)
        {
            return _context.Cafes.Any(e => e.Id == id);
        }
    }
}

FastFood/Views/Cafe/Create.cshtml
@model FastFood.Models.Cafe

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Cafe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="file" name="cafeFiles" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FastFood/Views/Cafe/Delete.cshtml
@model FastFood.Models.Cafe

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cafe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FastFood/Views/Cafe/Details.cshtml
@model FastFood.Models.CafeDetailsViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Cafe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cafe.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cafe.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cafe.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cafe.Description)
        </dd>
        <dt>
            Изображения
        </dt>
        @foreach (var i in Model.Cafe.Photos)
        {
            <dd>
                @{
                    var path = "/images/" + i.Name;
                }
                <img width="200" height="200" src="@path"/>
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.Cafe.Rating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cafe.Rating)
        </dd>
    </dl>
</div>

<div id="reviews-@Model.Cafe.Id">
    <b>Reviews (@Model.Cafe.Review)</b>
    @foreach (var r in Model.Cafe.Reviews)
    {
        <div>@r.ReviewText<br /></div>
    }
    <a onclick="openRepliesForm(@Model.Cafe.Id)" style="cursor: pointer">Send Review</a>
</div>
<div id="themediv-@Model.Cafe.Id" style="display: none">
    <textarea id="themetext-@Model.Cafe.Id"></textarea>
    <input type="button" id="themeReply"
           onclick="sendReply('@Model.Cafe.Id')" value="Send" />
</div>

@*<div>
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@
@section Scripts
    {
    <script>
        function openRepliesForm(cafeId) {
            $('#themediv-' + cafeId).show();
        }

        function sendReply(cafeId) {
            $.ajax(
                {
                    url: '@Url.Action("Review", "Cafe")',
                    type: 'POST',
                    data: { 'cafeId': cafeId, 'reviewText': $('#themetext-' + cafeId).val() },
                    success: function (data) { addReply(data, cafeId) },
                    error: function (data) { alert(data) }
                });
        }

        function addReply(data, cafeId) {
            $('#reviews-' + cafeId).append('<div' + data + '</br></div>');
        }

        $(document).on('click', '#sendRely', function () {
            $(this).hide();
        });
    </script>
}

FastFood/Views/Cafe/Edit.cshtml
@model FastFood.Models.Cafe

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Cafe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FastFood/Views/Cafe/Index.cshtml
@model IEnumerable<FastFood.Models.Cafe>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @if (User.Identity.IsAuthenticated)
    {
        <a asp-action="Create">Добавить Заведение</a>
    }
    
</p>
<table class="table" id="myTable" data-page-length='20'>
    <thead>
    <tr>
        <th>
            Название
        </th>
        <th>
            Описание
        </th>
        <th>
            Рейтинг
        </th>
        <th>
            Отзывы
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Review)
            </td>
            <td>
                @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |

            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
            </td>
        </tr>
    }
    </tbody>
</table>

@section Scripts
{
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable();
        } );
    </script>
}